apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-api-server
type: Opaque
data:
  kafka.username: {{ .Values.env.kafka.username | b64enc }}
  kafka.password: {{ .Values.env.kafka.password | b64enc }}
  mongodb.rootUsername: {{ .Values.env.mongodb.rootUsername | b64enc }}
  mongodb.rootPassword: {{ .Values.env.mongodb.rootPassword | b64enc }}
