apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-web-server
type: Opaque
data:
  kafka.username: {{ .Values.env.kafka.username | b64enc }}
  kafka.password: {{ .Values.env.kafka.password | b64enc }}
