apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web-server
  labels:
    app: {{ .Release.Name }}-web-server
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
  selector:
    app: {{ .Release.Name }}-web-server
